### ISSUE TITLE
Feature request: Additional Tab Behavior

### ISSUE THREAD

**Issue by okwichu** [GeorgeSG/arc-cli#3]
Hi, I'm building some automation around arc-cli that requires a couple of features that I can't figure out how to get out of `arc-cli`.  In summary, I want to find a way to extract a couple more dimensions from the `list-tabs` command:

* I need to get the space of each tab.  I'd prefer also being able to slice tabs by profile, but I've not seen any AppleScript examples anywhere that offer that, so I suspect it might not be exposed from the Arc API itself.

* I would like to get the status of each tab -- specifically I would like to tell if `topApp` or `pinned` tabs are cold or if have been recently loaded and can be considered "active".

Are either of these possible in Arc today (I wasn't able to find actual API docs from TBC)?  I'd be happy to take a crack at them myself and submit a PR if it's not a trivial feature request to implement.

**Comment by GeorgeSG** [comment]
To be honest, I don't know if the things you're suggesting are possible. I'm not aware of any API docs, what's implemented here is mostly done by reverse engineering and guessing.

I'll definitely accept PRs if someone figures it out :)

**Comment by CB-JasonArnold** [comment]
The only "API docs" I'm aware of come from loading the dictionary in the script editor, which a colleague just showed me how to do today :). Thank you!  You can resolve this issue at will, I appreciate the confirmation.
